apiVersion: v1
kind: Pod
metadata:
  name: alpha-pod
spec:
  containers:
    - name: alpha-pod-container
      image: nginx:1.7.9
      ports:
        - containerPort: 80
          protocol: TCP
          name: web