apiVersion: v1
kind: Service
metadata:
  labels:
    app: express-app
  name: express-service-secret
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: express-app-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment-secret
  labels:
    app: express-app-secret
    tier: app
    response: cold
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        app: express-app-secret
        tier: app
    spec:
      containers:
        - name: express-app-container
          image: partyk1d24/hello-express:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DEPLOY_TYPE
              valueFrom:
                secretKeyRef:
                  name: greeting
                  key: mySecret
          ports:
            - containerPort: 3000
              protocol: TCP
              name: express-endpnt