apiVersion: v1
kind: Service
metadata:
  labels:
    app: express-app
  name: express-service-config
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: express-app-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: express-config
data:
  # property-like keys; each key maps to a simple value
  greeting: "Hellooooooo nurse"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment-config
  labels:
    app: express-app-config
    tier: app
    response: cold
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        app: express-app-config
        tier: app
    spec:
      containers:
        - name: express-app-container
          image: partyk1d24/hello-express:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DEPLOY_TYPE
              valueFrom:
                configMapKeyRef:
                  name: express-config          # The ConfigMap this value comes from.
                  key: greeting

          ports:
            - containerPort: 3000
              protocol: TCP
              name: express-endpnt