apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app: simple-site
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: ...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-site-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-site
  template:
    metadata:
      labels:
        app: simple-site
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pg_data
          envFrom:
            - configMapRef:
                name: db-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
              claimName: test-volume-other-claim
#        - name: postgredb
#          hostPath:
#            path: /Users/jackiegleason/pg_data/db