apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume-other
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/jackiegleason/pg_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume-other-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: simple-site-service
  labels:
    app: simple-site
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: simple-site